/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"time"
)

// Api error.
type ApiError struct {

	// Gets or sets api error code.
	Code string `json:"Code,omitempty"`

	// Gets or sets error message.
	Message string `json:"Message,omitempty"`

	// Gets or sets error description.
	Description string `json:"Description,omitempty"`

	// Gets or sets server datetime.
	DateTime time.Time `json:"DateTime,omitempty"`

	// Gets or sets inner error.
	InnerError *ApiError `json:"InnerError,omitempty"`
}
