/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// The list of fonts, available for document processing.
type AvailableFontsResponse struct {

	// Gets or sets request Id.
	RequestId string `json:"RequestId,omitempty"`

	// Gets or sets the list of addititional fonts, provided by aspose team.
	AdditionalFonts []FontInfo `json:"AdditionalFonts,omitempty"`

	// Gets or sets custom user fonts (from user file storage). To use them, you should specify \"fontsLocation\" parameter in any request.
	CustomFonts []FontInfo `json:"CustomFonts,omitempty"`

	// Gets or sets the list of system fonts, availiable on the server.
	SystemFonts []FontInfo `json:"SystemFonts,omitempty"`
}
