/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// container class for individual bookmarks outline level.
type BookmarksOutlineLevelData struct {

	// Gets or sets specify the bookmark's name.
	Name string `json:"Name,omitempty"`

	// Gets or sets specify the bookmark's level.
	BookmarksOutlineLevel int32 `json:"BookmarksOutlineLevel"`
}
