/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// This response should be returned by the service when handling:  GET bookmarks/{bookmarkName}.
type BookmarkResponse struct {

	// Gets or sets request Id.
	RequestId string `json:"RequestId,omitempty"`

	// Gets or sets bookmark.
	Bookmark *Bookmark `json:"Bookmark,omitempty"`
}
