/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// DTO for bookmark updating.
type BookmarkData struct {

	// Gets or sets the name of the bookmark.
	Name string `json:"Name,omitempty"`

	// Gets or sets the text enclosed in the bookmark.
	Text string `json:"Text,omitempty"`
}
