/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Represents a border of an object.
type Border struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets the border type.             
	BorderType string `json:"BorderType,omitempty"`

	// Gets or sets the border color.             
	Color *XmlColor `json:"Color,omitempty"`

	// Gets or sets distance of the border from text or from the page edge in points.
	DistanceFromText float64 `json:"DistanceFromText,omitempty"`

	// Gets or sets the border style.
	LineStyle string `json:"LineStyle,omitempty"`

	// Gets or sets the border width in points.
	LineWidth float64 `json:"LineWidth,omitempty"`

	// Gets or sets a value indicating whether the border has a shadow.
	Shadow bool `json:"Shadow,omitempty"`
}
