/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// This response should be returned by the service when handling: PUT http://api.aspose.com/v4.0/words/classify.
type ClassificationResponse struct {

	// Gets or sets request Id.
	RequestId string `json:"RequestId,omitempty"`

	// Gets or sets best class name.
	BestClassName string `json:"BestClassName,omitempty"`

	// Gets or sets best class probability.
	BestClassProbability float64 `json:"BestClassProbability,omitempty"`

	// Gets or sets array of best classes results.
	BestResults []ClassificationResult `json:"BestResults,omitempty"`
}
