/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"time"
)

// Container class for compare documents.
type CompareData struct {

	// Gets or sets path to document to compare at the server.
	ComparingWithDocument string `json:"ComparingWithDocument,omitempty"`

	// Gets or sets initials of the author to use for revisions.
	Author string `json:"Author,omitempty"`

	// Gets or sets the date and time to use for revisions.             
	DateTime time.Time `json:"DateTime,omitempty"`
}
