/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Container for the document's statistical data.
type DocumentStatData struct {

	// Gets or sets total count of words in the document.
	WordCount int32 `json:"WordCount"`

	// Gets or sets total count of paragraphs in the document.
	ParagraphCount int32 `json:"ParagraphCount"`

	// Gets or sets total count of pages in the document.
	PageCount int32 `json:"PageCount"`

	// Gets or sets detailed statistics of footnotes.
	FootnotesStatData *FootnotesStatData `json:"FootnotesStatData,omitempty"`

	// Gets or sets detailed statistics of all pages.
	PageStatData []PageStatData `json:"PageStatData,omitempty"`
}
