/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Represents a position in the document tree.
type DocumentPosition struct {

	// Gets or sets link to  node.
	Node *NodeLink `json:"Node,omitempty"`

	// Gets or sets offset into the node.
	Offset int32 `json:"Offset,omitempty"`
}
