/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Represents a document which will be appended to the original resource document.
type DocumentEntry struct {

	// Gets or sets path to document to append at the server.
	Href string `json:"Href,omitempty"`

	// Gets or sets defines which formatting will be used: appended or destination document.Can be KeepSourceFormatting or UseDestinationStyles.
	ImportFormatMode string `json:"ImportFormatMode,omitempty"`
}
