/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Represents Words document DTO.
type Document struct {

	// Gets or sets a list of links that originate from this document.
	Links []Link `json:"Links,omitempty"`

	// Gets or sets the name of the file.
	FileName string `json:"FileName,omitempty"`

	// Gets or sets the original format of the document.
	SourceFormat string `json:"SourceFormat"`

	// Gets or sets a value indicating whether returns true if the document is encrypted and requires a password to open.
	IsEncrypted bool `json:"IsEncrypted"`

	// Gets or sets a value indicating whether returns true if the document contains a digital signature. This property merely informs that a digital signature is present on a document, but it does not specify whether the signature is valid or not.
	IsSigned bool `json:"IsSigned"`

	// Gets or sets returns document properties.
	DocumentProperties *DocumentProperties `json:"DocumentProperties,omitempty"`
}
