/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Words document property DTO.
type DocumentProperty struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets a value indicating whether flag indicates whether the property is built-in or not. If true the property is built-in, if false the property is custom.
	BuiltIn bool `json:"BuiltIn,omitempty"`

	// Gets or sets name of the document property.
	Name string `json:"Name,omitempty"`

	// Gets or sets string value of the document property.
	Value string `json:"Value,omitempty"`
}
