/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Represents a list of documents which will be appended to the original resource document.
type DocumentEntryList struct {

	// Gets or sets list of documents.
	DocumentEntries []DocumentEntry `json:"DocumentEntries,omitempty"`
}
