/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Container class for Downsample options.
type DownsampleOptionsData struct {

	// Gets or sets specifies whether images should be downsampled.
	DownsampleImages bool `json:"DownsampleImages,omitempty"`

	// Gets or sets specifies the resolution in pixels per inch which the images should be downsampled to.
	Resolution int32 `json:"Resolution,omitempty"`

	// Gets or sets specifies the threshold resolution in pixels per inch. If resolution of an image in the document is less than threshold value, the downsampling algorithm will not be applied. A value of 0 means the threshold check is not used and all images that can be reduced in size are downsampled.
	ResolutionThreshold int32 `json:"ResolutionThreshold,omitempty"`
}
