/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Represents Drawing Object DTO.
type DrawingObject struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets node id.
	NodeId string `json:"NodeId,omitempty"`

	// Gets or sets height of the drawing object in points.
	Height float64 `json:"Height,omitempty"`

	// Gets or sets link to image data. Can be null if shape does not have an image.
	ImageDataLink *WordsApiLink `json:"ImageDataLink,omitempty"`

	// Gets or sets distance in points from the origin to the left side of the image.             
	Left float64 `json:"Left,omitempty"`

	// Gets or sets link to ole object. Can be null if shape does not have ole data.
	OleDataLink *WordsApiLink `json:"OleDataLink,omitempty"`

	// Gets or sets specifies where the distance to the image is measured from.             
	RelativeHorizontalPosition string `json:"RelativeHorizontalPosition,omitempty"`

	// Gets or sets specifies where the distance to the image measured from.
	RelativeVerticalPosition string `json:"RelativeVerticalPosition,omitempty"`

	// Gets or sets a list of links that originate from this .
	RenderLinks []WordsApiLink `json:"RenderLinks,omitempty"`

	// Gets or sets distance in points from the origin to the top side of the image.
	Top float64 `json:"Top,omitempty"`

	// Gets or sets width of the drawing objects in points.
	Width float64 `json:"Width,omitempty"`

	// Gets or sets specifies how to wrap text around the image.
	WrapType string `json:"WrapType,omitempty"`
}
