/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"time"
)

// The error details
type ErrorDetails struct {

	// The request id
	RequestId string `json:"RequestId,omitempty"`

	// Date
	Date time.Time `json:"Date"`
}
