/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Font info.
type FontInfo struct {

	// Gets or sets family name of the font.
	FontFamilyName string `json:"FontFamilyName,omitempty"`

	// Gets or sets full name of the font.
	FullFontName string `json:"FullFontName,omitempty"`

	// Gets or sets version string of the font.
	Version string `json:"Version,omitempty"`

	// Gets or sets path to the font file if any.
	FilePath string `json:"FilePath,omitempty"`
}
