/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Container for the footnotes statistical data.
type FootnotesStatData struct {

	// Gets or sets total count of words in footnotes.
	WordCount int32 `json:"WordCount"`

	// Gets or sets total count of paragraphs in footnotes.
	ParagraphCount int32 `json:"ParagraphCount"`
}
