/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// FormField text input element.
type FormFieldTextInput struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets node id.
	NodeId string `json:"NodeId,omitempty"`

	// Gets or sets true if references to the specified form field are automatically updated whenever the field is exited.
	CalculateOnExit bool `json:"CalculateOnExit,omitempty"`

	// Gets or sets true if a form field is enabled.
	Enabled bool `json:"Enabled,omitempty"`

	// Gets or sets returns or sets an entry macro name for the form field.
	EntryMacro string `json:"EntryMacro,omitempty"`

	// Gets or sets returns or sets an exit macro name for the form field.
	ExitMacro string `json:"ExitMacro,omitempty"`

	// Gets or sets returns or sets the text that's displayed in a message box when the form field has the focus and the user presses F1.
	HelpText string `json:"HelpText,omitempty"`

	// Gets or sets the form field name.
	Name string `json:"Name,omitempty"`

	// Gets or sets specifies the source of the text that's displayed in a message box when a form field has the focus and the user presses F1.
	OwnHelp bool `json:"OwnHelp,omitempty"`

	// Gets or sets specifies the source of the text that's displayed in the status bar when a form field has the focus.
	OwnStatus bool `json:"OwnStatus,omitempty"`

	// Gets or sets returns or sets the text that's displayed in the status bar when a form field has the focus.
	StatusText string `json:"StatusText,omitempty"`

	// Gets or sets maximum length for the text field. Zero when the length is not limited.
	MaxLength int32 `json:"MaxLength,omitempty"`

	// Gets or sets the default string or a calculation expression of a text form field.
	TextInputDefault string `json:"TextInputDefault,omitempty"`

	// Gets or sets returns or sets the text formatting for a text form field.
	TextInputFormat string `json:"TextInputFormat,omitempty"`

	// Gets or sets the type of a text form field.
	TextInputType string `json:"TextInputType,omitempty"`
}
