/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Allows to specify additional System.Drawing.Graphics quality options.
type GraphicsQualityOptionsData struct {

	// Gets or sets a value that specifies how composited images are drawn to this Graphics.
	CompositingMode string `json:"CompositingMode,omitempty"`

	// Gets or sets the rendering quality of composited images drawn to this Graphics.
	CompositingQuality string `json:"CompositingQuality,omitempty"`

	// Gets or sets the interpolation mode associated with this Graphics.
	InterpolationMode string `json:"InterpolationMode,omitempty"`

	// Gets or sets the rendering quality for this Graphics.
	SmoothingMode string `json:"SmoothingMode,omitempty"`

	// Gets or sets text layout information (such as alignment, orientation and tab stops) display manipulations (such as ellipsis insertion and national digit substitution) and OpenType features.
	StringFormat *StringFormatData `json:"StringFormat,omitempty"`

	// Gets or sets the rendering mode for text associated with this Graphics.
	TextRenderingHint string `json:"TextRenderingHint,omitempty"`
}
