/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// container class for fixed html save options.
type HtmlFixedSaveOptionsData struct {

	// Gets or sets a value determining how colors are rendered. { Normal | Grayscale}.
	ColorMode string `json:"ColorMode,omitempty"`

	// Gets or sets format of save.
	SaveFormat string `json:"SaveFormat,omitempty"`

	// Gets or sets name of destination file.
	FileName string `json:"FileName,omitempty"`

	// Gets or sets a value determining how DrawingML shapes are rendered. { Fallback | DrawingML }.
	DmlRenderingMode string `json:"DmlRenderingMode,omitempty"`

	// Gets or sets a value determining how DrawingML effects are rendered. { Simplified | None | Fine }.
	DmlEffectsRenderingMode string `json:"DmlEffectsRenderingMode,omitempty"`

	// Gets or sets controls zip output or not. Default value is false.
	ZipOutput bool `json:"ZipOutput,omitempty"`

	// Gets or sets a value determining whether the Aspose.Words.Properties.BuiltInDocumentProperties.LastSavedTime property is updated before saving.
	UpdateLastSavedTimeProperty bool `json:"UpdateLastSavedTimeProperty,omitempty"`

	// Gets or sets value determining whether content of  is updated before saving.
	UpdateSdtContent bool `json:"UpdateSdtContent,omitempty"`

	// Gets or sets a value determining if fields should be updated before saving the document to a fixed page format. Default value for this property is. true
	UpdateFields bool `json:"UpdateFields,omitempty"`

	// Gets or sets determines the quality of the JPEG images inside PDF document.
	JpegQuality int32 `json:"JpegQuality,omitempty"`

	// Gets or sets allows to specify metafile rendering options.
	MetafileRenderingOptions *MetafileRenderingOptionsData `json:"MetafileRenderingOptions,omitempty"`

	// Gets or sets indicates the symbol set that is used to represent numbers while rendering to fixed page formats.
	NumeralFormat string `json:"NumeralFormat,omitempty"`

	// Gets or sets flag indicates whether it is required to optimize output of XPS. If this flag is set redundant nested canvases and empty canvases are removed, also neighbor glyphs with the same formatting are concatenated. Note: The accuracy of the content display may be affected if this property is set to true.  Default is false.
	OptimizeOutput bool `json:"OptimizeOutput,omitempty"`

	// Gets or sets determines number of pages to render.
	PageCount int32 `json:"PageCount,omitempty"`

	// Gets or sets determines 0-based index of the first page to render.
	PageIndex int32 `json:"PageIndex,omitempty"`

	// Gets or sets specifies prefix which is added to all class names in style.css file. Default value is \"aw\".
	CssClassNamesPrefix string `json:"CssClassNamesPrefix,omitempty"`

	// Gets or sets encoding.
	Encoding string `json:"Encoding,omitempty"`

	// Gets or sets specifies whether the CSS (Cascading Style Sheet) should be embedded into Html document.
	ExportEmbeddedCss bool `json:"ExportEmbeddedCss,omitempty"`

	// Gets or sets specifies whether fonts should be embedded into Html document in Base64 format.
	ExportEmbeddedFonts bool `json:"ExportEmbeddedFonts,omitempty"`

	// Gets or sets specifies whether images should be embedded into Html document in Base64 format.
	ExportEmbeddedImages bool `json:"ExportEmbeddedImages,omitempty"`

	// Gets or sets indication of whether form fields are exported as interactive items (as 'input' tag) rather than converted to text or graphics.
	ExportFormFields bool `json:"ExportFormFields,omitempty"`

	// Gets or sets specifies export format of fonts.
	FontFormat string `json:"FontFormat,omitempty"`

	// Gets or sets specifies the horizontal alignment of pages in an HTML document. Default value is HtmlFixedHorizontalPageAlignment.Center.
	PageHorizontalAlignment string `json:"PageHorizontalAlignment,omitempty"`

	// Gets or sets specifies the margins around pages in an HTML document. The margins value is measured in points and should be equal to or greater than 0. Default value is 10 points.
	PageMargins float64 `json:"PageMargins,omitempty"`

	// Gets or sets specifies the physical folder where resources are saved when exporting a document.
	ResourcesFolder string `json:"ResourcesFolder,omitempty"`

	// Gets or sets specifies the name of the folder used to construct resource URIs.
	ResourcesFolderAlias string `json:"ResourcesFolderAlias,omitempty"`

	// Gets or sets flag indicates whether \"@font-face\" CSS rules should be placed into a separate file \"fontFaces.css\" when a document is being saved with external stylesheet (that is, when Aspose.Words.Saving.HtmlFixedSaveOptions.ExportEmbeddedCss is false). Default value is false, all CSS rules are written into single file \"styles.css\".
	SaveFontFaceCssSeparately bool `json:"SaveFontFaceCssSeparately,omitempty"`

	// Gets or sets specifies whether border around pages should be shown.
	ShowPageBorder bool `json:"ShowPageBorder,omitempty"`
}
