/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Hyperlink element.
type Hyperlink struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets hypelink's display text.
	DisplayText string `json:"DisplayText,omitempty"`

	// Gets or sets value.
	Value string `json:"Value,omitempty"`
}
