/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Contains data for load web document.
type LoadWebDocumentData struct {

	// Gets or sets web document url.
	LoadingDocumentUrl string `json:"LoadingDocumentUrl,omitempty"`

	// Gets or sets save options.
	SaveOptions *SaveOptionsData `json:"SaveOptions,omitempty"`
}
