/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// container class for options of metafile rendering.
type MetafileRenderingOptionsData struct {

	// Gets or sets determines how EMF+ Dual metafiles should be rendered.
	EmfPlusDualRenderingMode string `json:"EmfPlusDualRenderingMode,omitempty"`

	// Gets or sets a value determining whether or not the raster operations should be emulated.             
	EmulateRasterOperations bool `json:"EmulateRasterOperations,omitempty"`

	// Gets or sets determines how metafile images should be rendered.
	RenderingMode string `json:"RenderingMode,omitempty"`

	// Gets or sets determines how WMF metafiles with embedded EMF metafiles should be rendered.
	UseEmfEmbeddedToWmf bool `json:"UseEmfEmbeddedToWmf,omitempty"`

	// Gets or sets a value determining whether or not to scale fonts in WMF metafile according to metafile size on the page. The default value is true.
	ScaleWmfFontsToMetafileSize bool `json:"ScaleWmfFontsToMetafileSize,omitempty"`
}
