/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// OfficeMath object.
type OfficeMathObject struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets node id.
	NodeId string `json:"NodeId,omitempty"`

	// Gets or sets content of footnote.
	Content *StoryChildNodes `json:"Content,omitempty"`

	// Gets or sets /sets Office Math display format type which represents whether an equation is displayed inline with the text or displayed on its own line.
	DisplayType string `json:"DisplayType,omitempty"`

	// Gets or sets /sets Office Math justification.
	Justification string `json:"Justification,omitempty"`

	// Gets or sets type Aspose.Words.Math.OfficeMath.MathObjectType of this Office Math object.
	MathObjectType string `json:"MathObjectType,omitempty"`
}
