/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// container class for outline options.
type OutlineOptionsData struct {

	// Gets or sets allows to specify individual bookmarks outline level.
	BookmarksOutlineLevels []BookmarksOutlineLevelData `json:"BookmarksOutlineLevels,omitempty"`

	// Gets or sets specifies the default level in the document outline at which to display Word bookmarks.
	DefaultBookmarksOutlineLevel int32 `json:"DefaultBookmarksOutlineLevel,omitempty"`

	// Gets or sets a value determining whether or not to create missing outline levels     when the document is exported.     Default value for this property is false.
	CreateMissingOutlineLevels bool `json:"CreateMissingOutlineLevels,omitempty"`

	// Gets or sets specifies whether or not to create outlines for headings (paragraphs formatted     with the Heading styles) inside tables.
	CreateOutlinesForHeadingsInTables bool `json:"CreateOutlinesForHeadingsInTables,omitempty"`

	// Gets or sets specifies how many levels in the document outline to show expanded when the file is viewed.
	ExpandedOutlineLevels int32 `json:"ExpandedOutlineLevels,omitempty"`

	// Gets or sets specifies how many levels of headings (paragraphs formatted with the Heading styles) to include in the document outline.
	HeadingsOutlineLevels int32 `json:"HeadingsOutlineLevels,omitempty"`
}
