/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Class is used for insert page number request building.
type PageNumber struct {

	// Gets or sets page number format, e.g. \"{PAGE} of {NUMPAGES}\".
	Format string `json:"Format,omitempty"`

	// Gets or sets text alignment, possible values are left, right, center or justify.
	Alignment string `json:"Alignment,omitempty"`

	// Gets or sets a value indicating whether if true the page number is added at the top of the page, else at the bottom.
	IsTop bool `json:"IsTop"`

	// Gets or sets a value indicating whether if true the page number is added on first page too.
	SetPageNumberOnFirstPage bool `json:"SetPageNumberOnFirstPage"`
}
