/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Paragraph element.
type ParagraphInsert struct {

	// Gets or sets paragraph's text.
	Text string `json:"Text,omitempty"`
}
