/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// container class for details of encryption.
type PdfEncryptionDetailsData struct {

	// Gets or sets specifies the encryption algorithm to use.
	EncryptionAlgorithm string `json:"EncryptionAlgorithm,omitempty"`

	// Gets or sets specifies the owner password for the encrypted PDF document.
	OwnerPassword string `json:"OwnerPassword,omitempty"`

	// Gets or sets specifies the operations that are allowed to a user on an encrypted PDF document.
	Permissions string `json:"Permissions,omitempty"`

	// Gets or sets specifies the user password required for opening the encrypted PDF document.
	UserPassword string `json:"UserPassword,omitempty"`
}
