/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Preferred width.
type PreferredWidth struct {

	// Gets or sets the unit of measure used for this preferred width value.
	Type_ string `json:"Type"`

	// Gets or sets the preferred width value. The unit of measure is specified in the  property.
	Value float64 `json:"Value,omitempty"`
}
