/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Container for the data about protection of the document.
type ProtectionData struct {

	// Gets or sets type of the protection.
	ProtectionType string `json:"ProtectionType,omitempty"`
}
