/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Request on changing of protection.
type ProtectionRequest struct {

	// Gets or sets current password.
	Password string `json:"Password,omitempty"`

	// Gets or sets new password.
	NewPassword string `json:"NewPassword,omitempty"`

	// Gets or sets new type of protection.
	ProtectionType string `json:"ProtectionType,omitempty"`
}
