/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Range element.
type RangeDocument struct {

	// Gets or sets name for new document.
	DocumentName string `json:"DocumentName,omitempty"`
}
