/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Class for document replace text request building.
type ReplaceTextParameters struct {

	// Gets or sets old text value (or regex pattern ) to replace.
	OldValue string `json:"OldValue,omitempty"`

	// Gets or sets new text value to replace by.
	NewValue string `json:"NewValue,omitempty"`

	// Gets or sets a value indicating whether flag, true means the search is case-sensitive; false means the search is not case-sensitive.
	IsMatchCase bool `json:"IsMatchCase"`

	// Gets or sets a value indicating whether flag, means that only whole word matched are replaced.
	IsMatchWholeWord bool `json:"IsMatchWholeWord"`

	// Gets or sets a value indicating whether flag, means that  contains regex expression.
	IsOldValueRegex bool `json:"IsOldValueRegex"`
}
