/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Range element.
type ReplaceRange struct {

	// Gets or sets range's text.
	Text string `json:"Text,omitempty"`

	// Gets or sets range's text type.
	TextType string `json:"TextType,omitempty"`
}
