/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Response for \"Replace text\" action.
type ReplaceTextResponse struct {

	// Gets or sets request Id.
	RequestId string `json:"RequestId,omitempty"`

	// Gets or sets link to the document.
	DocumentLink *FileLink `json:"DocumentLink,omitempty"`

	// Gets or sets number of occurrences of the captured text in the document.
	Matches int32 `json:"Matches,omitempty"`
}
