/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Section element.
type Section struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets child nodes.
	ChildNodes []NodeLink `json:"ChildNodes,omitempty"`

	// Gets or sets link to HeaderFooters resource.
	HeaderFooters *LinkElement `json:"HeaderFooters,omitempty"`

	// Gets or sets link to PageSetup resource.
	PageSetup *LinkElement `json:"PageSetup,omitempty"`

	// Gets or sets link to Paragraphs resource.
	Paragraphs *LinkElement `json:"Paragraphs,omitempty"`

	// Gets or sets link to Tables resource.
	Tables *LinkElement `json:"Tables,omitempty"`
}
