/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Response for the request of the document's statistical data.
type StatDataResponse struct {

	// Gets or sets request Id.
	RequestId string `json:"RequestId,omitempty"`

	// Gets or sets link to the document.
	DocumentLink *FileLink `json:"DocumentLink,omitempty"`

	// Gets or sets statistical data of the document.
	StatData *DocumentStatData `json:"StatData,omitempty"`
}
