/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Child nodes of  or .
type StoryChildNodes struct {

	// Gets or sets child nodes.
	ChildNodes []NodeLink `json:"ChildNodes,omitempty"`
}
