/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Allows to specify System.Drawing.StringFormat options.
type StringFormatData struct {

	// Gets or sets horizontal alignment of the string.
	Alignment string `json:"Alignment,omitempty"`

	// Gets or sets a System.Drawing.StringFormatFlags enumeration that contains formatting information.
	FormatFlags string `json:"FormatFlags,omitempty"`

	// Gets or sets the System.Drawing.Text.HotkeyPrefix object for this System.Drawing.StringFormat object.
	HotkeyPrefix string `json:"HotkeyPrefix,omitempty"`

	// Gets or sets the vertical alignment of the string.
	LineAlignment string `json:"LineAlignment,omitempty"`

	// Gets or sets the System.Drawing.StringTrimming enumeration for this System.Drawing.StringFormat object.
	Trimming string `json:"Trimming,omitempty"`
}
