/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Table element.
type TableInsert struct {

	// Gets or sets table will be inserted before specified position.
	Position *DocumentPosition `json:"Position,omitempty"`

	// Gets or sets count of columns. Default is 2.
	ColumnsCount int32 `json:"ColumnsCount"`

	// Gets or sets count of rows. Default is 2.
	RowsCount int32 `json:"RowsCount"`
}
