/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Table cell element.
type TableCellInsert struct {

	// Gets or sets table cell will be inserted after cell with specified 0-based index.
	InsertAfter int32 `json:"InsertAfter,omitempty"`
}
