/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Table row element.
type TableRow struct {

	// Gets or sets link to the document.
	Link *WordsApiLink `json:"link,omitempty"`

	// Gets or sets node id.
	NodeId string `json:"NodeId,omitempty"`

	// Gets or sets provides access to the formatting properties of the row.
	RowFormat *TableRowFormat `json:"RowFormat,omitempty"`

	// Gets or sets collection of table's rows.
	TableCellList []TableCell `json:"TableCellList,omitempty"`
}
