/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Table row element.
type TableRowInsert struct {

	// Gets or sets table row will be inserted after row with specified 0-based index.
	InsertAfter int32 `json:"InsertAfter,omitempty"`

	// Gets or sets count of columns. Default is 1.
	ColumnsCount int32 `json:"ColumnsCount"`
}
