/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Class for insert watermark text request building.
type WatermarkText struct {

	// Gets or sets the watermark text.
	Text string `json:"Text,omitempty"`

	// Gets or sets the watermark rotation angle.
	RotationAngle float64 `json:"RotationAngle"`
}
