/*
 * Aspose.Words Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 19.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Base class for all responses.
type WordsResponse struct {

	// Gets or sets request Id.
	RequestId string `json:"RequestId,omitempty"`
}
